In [1]:
import numpy as np
from LogReg import LogReg

In [2]:
X = np.random.standard_normal((100, 1))
X.shape

(100, 1)

In [3]:
y = np.random.randint(0, 2, (100, 1))
y.shape

(100, 1)

In [4]:
X[0]

array([-1.01654572])

In [5]:
w = np.random.rand(X.shape[1] + 1)
w

array([0.58575375, 0.65335446])

In [8]:
m = X.shape[0]

ones = np.ones((m, 1))
X = np.hstack((ones, X))

z = np.array([np.dot(X[i], w) for i in range(m)])


g = lambda z: 1 / (1 + np.exp(-z))


g_z = g(z)

cost = (-1 / m) * (np.dot(y.T, np.log(g_z)) +
                   np.dot((1 - y).T, np.log(1 - g_z)))




In [9]:
cost

array([0.78407842])